#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#
#  Debian系 local deb install
#

---
# パッケージをインストールする際のコマンドラインを構築する。
# 非対話的にパッケージを導入するため, DEBIAN_FRONTEND=noninteractive を設定する。
- name: Build local deb install argv
  ansible.builtin.set_fact:
    pkgbld_deb_install_argv: >-
      {{
        [
          'env',
          'DEBIAN_FRONTEND=noninteractive',
          'apt-get',
          '-y',
          '-o',
          'DPkg::Lock::Timeout=' ~ (pkgbld_install_deb_lock_wait_seconds | string),
          '-o',
          'Dpkg::Options::=--force-confdef',
          '-o',
          'Dpkg::Options::=--force-confold',
          'install'
        ]
        +
        (
          pkgbld_source_files
          | default([])
          | map(attribute='path')
          | map('basename')
          | map('regex_replace', '^', pkgbld_install_dest_dir ~ '/')
          | list
        )
      }}

# Debian 系のローカル deb パッケージをautostart抑制下で一括導入する
#  autostart抑制を実施しない場合, 導入対象の deb パッケージが
#  サービスを自動起動するため, 導入対象の deb パッケージが
#  依存するサービスが自動的に起動し, 導入に失敗することがある
- name: Install local deb packages in one transaction with service autostart suppressed
  become: true
  block:

    # 一時的に policy-rc.d を作成し, パッケージ導入(入れ替え)中の
    # サービス自動起動を抑制する
    - name: Create temporary policy-rc.d to suppress service autostart
      ansible.builtin.copy:
        dest: /usr/sbin/policy-rc.d
        mode: "0755"
        content: |
          #!/bin/sh
          exit 101

    # Debian 系のローカル deb パッケージを一括導入する
    - name: Install local deb packages in one transaction
      ansible.builtin.command:
        argv: "{{ pkgbld_deb_install_argv }}"
      register: pkgbld_deb_install_cmd
      changed_when: pkgbld_deb_install_cmd.rc == 0
  always:
    # 修復後に一時的に作成した policy-rc.d を削除する
    - name: Remove temporary policy-rc.d
      ansible.builtin.file:
        path: /usr/sbin/policy-rc.d
        state: absent
