#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  virtual cluster tenant用CoreDNSコンテナイメージをK8sノードへ配布する
#
---

- name: "Register vc-tenant-dns image on control-plane nodes"  # noqa: var-naming[no-role-prefix]
  ansible.builtin.include_role:
    name: k8s-register-image
    tasks_from: register-control-plane.yml
  vars:
    k8s_register_image_components:
      vc_tenant_dns: "{{ k8s_vc_tenant_dns_output_dir_on_control_host }}/{{ k8s_vc_tenant_dns_image_file }}"
    k8s_register_image_expected_images:
      vc_tenant_dns: "{{ k8s_vc_tenant_dns_image }}"
    k8s_register_image_auto_discover_control_plane_hosts: true
    k8s_register_image_cluster_key: "{{ k8s_ctrlplane_endpoint }}"
    k8s_register_image_remote_cache_dir: "{{ k8s_vc_tenant_dns_remote_cache_dir }}"
    k8s_register_image_unqualified_image_registry: "{{ k8s_vc_tenant_dns_unqualified_image_registry }}"
    k8s_register_image_cleanup_remote_tar: "{{ k8s_vc_tenant_dns_cleanup_remote_tar }}"

- name: "Discover target hosts for worker distribution"  # noqa: var-naming[no-role-prefix]
  ansible.builtin.include_role:
    name: k8s-register-image
    tasks_from: discover-target-hosts.yml
  vars:
    k8s_register_image_auto_discover_control_plane_hosts: true
    k8s_register_image_auto_discover_worker_hosts: true
    k8s_register_image_cluster_key: "{{ k8s_ctrlplane_endpoint }}"
    k8s_kubeconfig_to_discover_workers_path: "{{ k8s_vc_tenant_dns_kubeconfig_path }}"

- name: "Register vc-tenant-dns image on worker nodes"  # noqa: var-naming[no-role-prefix]
  ansible.builtin.include_role:
    name: k8s-register-image
    tasks_from: register-workers.yml
  vars:
    k8s_register_image_components:
      vc_tenant_dns: "{{ k8s_vc_tenant_dns_output_dir_on_control_host }}/{{ k8s_vc_tenant_dns_image_file }}"
    k8s_register_image_expected_images:
      vc_tenant_dns: "{{ k8s_vc_tenant_dns_image }}"
    k8s_register_image_remote_cache_dir: "{{ k8s_vc_tenant_dns_remote_cache_dir }}"
    k8s_register_image_unqualified_image_registry: "{{ k8s_vc_tenant_dns_unqualified_image_registry }}"
    k8s_register_image_cleanup_remote_tar: "{{ k8s_vc_tenant_dns_cleanup_remote_tar }}"
    k8s_register_image_auto_discover_control_plane_hosts: false
    k8s_register_image_auto_discover_worker_hosts: false
    k8s_register_image_skip_discovery: true
