#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  ロール固有変数のデフォルト値
#  group_vars/all/all.yml やhost_varsで上書き可能とするため,
#  ロール名/defaults/main.yml に定義している
---

# Filebeat ロールを有効化する。
logging_filebeat_enabled: true

#
# Filebeat パッケージ構築設定
#
# Filebeat 版数 (例: v8.17.3)
filebeat_version: "v8.17.3"
# Filebeat パッケージ構築ホスト
filebeat_build_host: "localhost"
# Filebeat パッケージ構築タイムアウト(秒)
filebeat_pkg_build_timeout_seconds: 7200
# Filebeat パッケージ構築監視ポーリング間隔(秒)
filebeat_pkg_build_loop_delay_seconds: 5
# Debian系でのaptロック待機時間(秒)
filebeat_install_deb_lock_wait_seconds: 600
# 既存 Filebeat パッケージ削除有無
filebeat_remove_existing_package: true
# コンテナビルド用ランタイム
filebeat_build_container_runtime: "docker"
# コンテナビルド用ネットワークモード
filebeat_build_container_network_mode: "host"
# Filebeat ビルド用コンテナイメージ
filebeat_build_container_image_debian: "ubuntu:24.04"
filebeat_build_container_image_rhel: "almalinux:9.6"
# Filebeat ビルド時のworkdir
filebeat_build_container_workdir: "/work"

#
# Filebeat 配置先設定
#
# Filebeat 設定ファイルを配置するディレクトリ
filebeat_config_dir: "/etc/filebeat"
# Filebeat 設定ファイルのパス
filebeat_config_file: "{{ filebeat_config_dir }}/filebeat.yml"
# Filebeat データディレクトリ
filebeat_data_dir: "/var/lib/filebeat"
# Filebeat ログディレクトリ
filebeat_logs_dir: "/var/log/filebeat"
# Filebeat systemd unit ファイルのパス
filebeat_systemd_unit_file: "/etc/systemd/system/filebeat.service"

#
# Filebeat 収集設定
#
# Filebeat の HTTP 接続バインドアドレス
filebeat_http_host: "0.0.0.0"
# Filebeat の HTTP 接続ポート番号
filebeat_http_port: 5066
# 収集対象ログファイルパスの一覧
filebeat_log_paths:
  - "/var/log/*.log"
  - "/var/log/syslog"
  - "/var/log/messages"
  - "/var/log/containers/*.log"
  - "/var/log/pods/*/*.log"
# 送信先 Logstash のホスト名/IPアドレス
# IPアドレス又はFQDNを指定すること
# *.local などの multicast DNS 名は, 環境により名前解決が不安定になるため指定しないこと
# 解決処理の対応関係: 1) logging_backend_host が未定義又は空文字列でない場合はその値を採用,
# 2) logging_backend_host が未定義又は空文字列の場合は logging_backend グループ先頭ホスト名を取得,
# 3) 先頭ホストの ansible_host が定義されていれば優先し, 未定義の場合はホスト名を採用。
filebeat_backend_host: >-
  {{
    (logging_backend_host | string | trim)
    if (logging_backend_host is defined and (logging_backend_host | string | trim | length) > 0)
    else (hostvars[groups['logging_backend'][0]].ansible_host | default(groups['logging_backend'][0]))
  }}
# 送信先 Logstash のポート番号
filebeat_backend_port: 5044

#
# 起動検証設定
#
# Filebeat コンテナの起動検証時の接続先ホスト名/IPアドレス
filebeat_wait_host: "127.0.0.1"
# Filebeat コンテナの起動検証時のタイムアウト値(単位: 秒)
filebeat_wait_timeout: 120
# Filebeat コンテナの起動検証時の待機開始遅延時間(単位: 秒)
filebeat_wait_delay: 2
# Filebeat コンテナの起動検証時のポーリング周期(単位: 秒)
filebeat_wait_sleep: 2
# Filebeat コンテナの起動検証時の接続元ホスト名/IPアドレス
filebeat_wait_delegate_to: "{{ inventory_hostname }}"
# Filebeat コンテナの起動検証時の再試行回数(単位: 回)
filebeat_wait_retries: 5
