#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  Metricbeat再起動ハンドラ
#
---

# 設定変更時に systemd サービスを再起動し, Metricbeat 設定を反映する。
- name: Restart Metricbeat service
  ansible.builtin.systemd:
    name: metricbeat
    state: restarted
    daemon_reload: true
  become: true
  changed_when: true
  listen: metricbeat_restart_service
