#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#

# /usr/local/binを作成
- name: "Create /usr/local/bin"
  ansible.builtin.file:
    path: "/usr/local/bin"
    state: directory
    owner: "root"
    group: "root"
    mode: "755"

# /usr/local/shareを作成
- name: "Create /usr/local/share"
  ansible.builtin.file:
    path: "/usr/local/share"
    state: directory
    owner: "root"
    group: "root"
    mode: "755"

# ローカルレジストリの永続データ格納先を作成
- name: "Create {{ docker_ce_registry_data_dir }}"
  ansible.builtin.file:
    path: "{{ docker_ce_registry_data_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
  when:
    - docker_ce_registry_enabled|default(false)|bool
