#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  タスクメイン部
#
#  include_tasksで他のタスクを読み込む
#

# 最初に変数設定を読み直す ( role単独で実行可能とするため )
- name: "Load Params"
  ansible.builtin.include_tasks: load-params.yml

# LDAP設定タスク実行条件の定義
# ldap_organization, ldap_domain, ldap_admin_password が設定され,
# ldap_admin_port が0でない場合にのみ実行される
- name: "Package"
  ansible.builtin.include_tasks: package.yml
  when:
    - ldap_organization | default('', true) | length > 0
    - ldap_domain | default('', true) | length > 0
    - ldap_admin_password | default('', true) | length > 0
    - ldap_admin_port | default(0, true) | int > 0

- name: "User Group"
  ansible.builtin.include_tasks: user_group.yml
  when:
    - ldap_organization | default('', true) | length > 0
    - ldap_domain | default('', true) | length > 0
    - ldap_admin_password | default('', true) | length > 0
    - ldap_admin_port | default(0, true) | int > 0

- name: "Directory"
  ansible.builtin.include_tasks: directory.yml
  when:
    - ldap_organization | default('', true) | length > 0
    - ldap_domain | default('', true) | length > 0
    - ldap_admin_password | default('', true) | length > 0
    - ldap_admin_port | default(0, true) | int > 0

- name: "Sysctl"
  ansible.builtin.include_tasks: sysctl.yml
  when:
    - ldap_organization | default('', true) | length > 0
    - ldap_domain | default('', true) | length > 0
    - ldap_admin_password | default('', true) | length > 0
    - ldap_admin_port | default(0, true) | int > 0

- name: "Service"
  ansible.builtin.include_tasks: service.yml
  when:
    - ldap_organization | default('', true) | length > 0
    - ldap_domain | default('', true) | length > 0
    - ldap_admin_password | default('', true) | length > 0
    - ldap_admin_port | default(0, true) | int > 0

- name: "Config"
  ansible.builtin.include_tasks: config.yml
  when:
    - ldap_organization | default('', true) | length > 0
    - ldap_domain | default('', true) | length > 0
    - ldap_admin_password | default('', true) | length > 0
    - ldap_admin_port | default(0, true) | int > 0
