#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  タスクメイン部
#
#  include_tasksで他のタスクを読み込む
#
---

# 最初に変数設定を読み直す ( role単独で実行可能とするため )
- name: "Load Params"
  ansible.builtin.include_tasks: load-params.yml
# 外部コマンドへ依存する処理より前に実行前提を検証する。
- name: "Package"
  ansible.builtin.include_tasks: package.yml
# 検証スクリプトと規則適用スクリプトの配置先を作成する。
- name: "Directory"
  ansible.builtin.include_tasks: directory.yml
# ホスト全体のネットワークを変更できる実行環境であることを確認する。
- name: "User Group"
  ansible.builtin.include_tasks: user_group.yml
# Elastic Stack各コンテナより先に共有Dockerネットワークを作成する。
- name: "Service"
  ansible.builtin.include_tasks: service.yml
# Dockerネットワーク作成後に送信規則と永続化サービスを設定する。
- name: "Config"
  ansible.builtin.include_tasks: config.yml
