#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#  ロール固有変数のデフォルト値
#  group_vars/all/all.yml やhost_varsで上書き可能とするため,
#  ロール名/defaults/main.yml に定義している
---
# 再起動後の応答待ちのタイムアウト時間 (秒)
reboot_timeout_sec: 600

# Kubernetes コントロールプレインノード使用ポート
k8s_control_plane_ports:
  - "6443/tcp"        # kube-apiserver
  - "10250/tcp"       # kubelet HTTPS
  - "10257/tcp"       # controller-manager
  - "10259/tcp"       # scheduler
  - "2379-2380/tcp"   # etcd (ローカル etcd の場合)

# Helmのアーカイブ名
k8s_helm_archive_name: "helm-v{{ k8s_helm_version }}-linux-amd64.tar.gz"
# HelmのダウンロードURL
k8s_helm_download_url: "https://get.helm.sh/{{ k8s_helm_archive_name }}"
# HelmのチェックサムダウンロードURL
k8s_helm_checksum_download_url: "{{ k8s_helm_download_url }}.sha256sum"
# Helm 最新版インストールスクリプトのURL
k8s_helm_install_script_url: "https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3"
# Helm用のコマンド補完設定を有効化する
k8s_helm_cli_completion_enabled: true
# Control Plane再構築時に既存Helmリポジトリを全削除する互換動作を有効化する
# 既定値falseでは既存リポジトリを保持し, Ciliumリポジトリだけを登録・更新する。
k8s_ctrlplane_helm_clear_repositories_enabled: false

# 共通CAで Kubernetes のルートCAを置き換えるか
k8s_shared_ca_replace_kube_ca: false

# Cilium CLI用のコマンド補完設定を有効化する
k8s_cilium_cli_completion_enabled: true
# Cilium CLI アーカイブ名とダウンロードURL
k8s_cilium_cli_archive_name: "cilium-linux-amd64.tar.gz"
k8s_cilium_cli_download_url: "https://github.com/cilium/cilium-cli/releases/latest/download/{{ k8s_cilium_cli_archive_name }}"
k8s_cilium_cli_checksum_url: "{{ k8s_cilium_cli_download_url }}.sha256sum"

# Cilium CNIのバージョン
k8s_cilium_version: "1.18.9"
# Cilium Helm Chartのバージョン
k8s_cilium_helm_chart_version: "{{ k8s_cilium_version }}"
# Ciliumコンテナイメージのバージョン
k8s_cilium_image_version: "v{{ k8s_cilium_version }}"
# Cilium Helm リポジトリ URL
k8s_cilium_helm_repo_url: "https://helm.cilium.io/"

# =============================================================
# Kubernetes API監査設定 (Kubernetes利用時のオプション)
# Kubernetes API ServerのAudit機能に関する設定
# Kubernetes API ServerのAudit機能:
#   https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/
# =============================================================
# Kubernetes API監査機能を有効にする場合は true を指定する
k8s_audit_enabled: false
#
# Kubernetes API監査ポリシーファイルのパス
k8s_audit_policy_path: "/etc/kubernetes/audit-policy.yaml"
#
# Kubernetes API監査ログ格納ディレクトリ
k8s_audit_log_dir: "/var/log/kubernetes/audit"
#
# Kubernetes API監査ログファイルのパス
k8s_audit_log_path: "/var/log/kubernetes/audit/audit.log"
#
# Kubernetes API監査ログを保持する最大日数 (単位: 日)
k8s_audit_log_max_age: 30
#
# Kubernetes API監査ログとして保持する最大ファイル数 (単位: 個)
k8s_audit_log_max_backup: 20
#
# Kubernetes API監査ログ1ファイルの最大サイズ (単位: MiB)
k8s_audit_log_max_size: 200
