#  -*- coding:utf-8-unix; mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  タスクメイン部
#
#  include_tasksで他のタスクを読み込む
#
---

# 最初に変数設定を読み直す ( role単独で実行可能とするため )
- name: "Load Params"
  ansible.builtin.include_tasks: load-params.yml

# パッケージ導入処理
- name: "Package"
  ansible.builtin.include_tasks: package.yml

# ファイル・ディレクトリ作成処理
- name: "Directory"
  ansible.builtin.include_tasks: directory.yml

# ユーザ・グループ作成処理
- name: "User Group"
  ansible.builtin.include_tasks: user_group.yml

# サービス起動処理
- name: "Service"
  ansible.builtin.include_tasks: service.yml

# 設定ファイル作成処理
- name: "Config"
  ansible.builtin.include_tasks: config.yml

# CiliumおよびHubble Relayの実行状態検証処理
- name: "Verify"
  ansible.builtin.include_tasks: verify.yml
