#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  unattended-upgrades サービス起動処理実体
#

# notify の apt_lock_defaults_restored に対応するハンドラ
- name: "Restore unattended-upgrades to distro default operation"
  listen: apt_lock_defaults_restored
  ansible.builtin.systemd:
    name: unattended-upgrades
    state: started
    daemon_reload: true
    enabled: true
  become: true
  failed_when: false

# notify の apt_lock_defaults_restored に対応するハンドラ
- name: "Restore apt daily timers to distro default operation"
  listen: apt_lock_defaults_restored
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  loop: "{{ apt_daily_timers_to_restore }}"
  become: true
  failed_when: false
