#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  タスクメイン部
#
#  include_tasksで他のタスクを読み込む
#
---

# 最初に変数設定を読み直す ( role単独で実行可能とするため )
- name: "Load Params"
  ansible.builtin.include_tasks: load-params.yml
  when:
    - radvd_nic | default('', true) | length > 0
    - ( radvd_nic | default('', true) ) in ansible_facts.interfaces
    - radvd_router_advertisement_prefix | default('', true) | length > 0

- name: "Package"
  ansible.builtin.include_tasks: package.yml
  when:
    - radvd_nic | default('', true) | length > 0
    - ( radvd_nic | default('', true) ) in ansible_facts.interfaces
    - radvd_router_advertisement_prefix | default('', true) | length > 0

- name: "Directory"
  ansible.builtin.include_tasks: directory.yml
  when:
    - radvd_nic | default('', true) | length > 0
    - ( radvd_nic | default('', true) ) in ansible_facts.interfaces
    - radvd_router_advertisement_prefix | default('', true) | length > 0

- name: "User Group"
  ansible.builtin.include_tasks: user_group.yml
  when:
    - radvd_nic | default('', true) | length > 0
    - ( radvd_nic | default('', true) ) in ansible_facts.interfaces
    - radvd_router_advertisement_prefix | default('', true) | length > 0

- name: "Config"
  ansible.builtin.include_tasks: config.yml
  when:
    - radvd_nic | default('', true) | length > 0
    - ( radvd_nic | default('', true) ) in ansible_facts.interfaces
    - radvd_router_advertisement_prefix | default('', true) | length > 0

- name: "Service"
  ansible.builtin.include_tasks: service.yml
  when:
    - radvd_nic | default('', true) | length > 0
    - ( radvd_nic | default('', true) ) in ansible_facts.interfaces
    - radvd_router_advertisement_prefix | default('', true) | length > 0
