#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  設定関連タスク
#
---

# Metricbeat の systemd unit を生成し, 導入時の起動定義を提供する。
- name: Render Metricbeat systemd unit
  ansible.builtin.template:
    src: metricbeat.service.j2
    dest: "{{ metricbeat_systemd_unit_file }}"
    mode: '0644'
  notify:
    - metricbeat_restart_service

# Metricbeat の設定ファイルを生成し, システムメトリクスの収集先を設定する。
- name: Render Metricbeat config
  ansible.builtin.template:
    src: metricbeat.yml.j2
    dest: "{{ metricbeat_config_file }}"
    mode: '0644'
  notify:
    - metricbeat_restart_service
