#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
# 共通設定タスク群
#   - タイムゾーン設定
#

#
# タイムゾーン設定
#

# hwclock コマンドが利用可能でない場合は, util-linux パッケージを導入する。
- name: Ensure hwclock command is available
  become: true
  ansible.builtin.package:
    name: util-linux
    state: present
  when: common_timezone is defined and ((common_timezone | default('', true) | length) > 0)

# タイムゾーン設定を反映する。
- name: "Setup time zone {{ common_timezone }}"
  community.general.timezone:
    name: "{{ common_timezone }}"
  when: common_timezone is defined and ( (common_timezone|default('',true)|length) > 0 )
