#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  ロール固有変数のデフォルト値
#  group_vars/all/all.yml やhost_varsで上書き可能とするため,
#  ロール名/defaults/main.yml に定義している
---

# Metricbeat ロールを有効化する。
logging_metricbeat_enabled: true

#
# Metricbeat パッケージ構築設定
#
# Metricbeat 版数 (例: v8.17.3)
metricbeat_version: "v8.17.3"
# Metricbeat パッケージ構築ホスト
metricbeat_build_host: "localhost"
# Metricbeat パッケージ構築タイムアウト(秒)
metricbeat_pkg_build_timeout_seconds: 7200
# Metricbeat パッケージ構築監視ポーリング間隔(秒)
metricbeat_pkg_build_loop_delay_seconds: 5
# Debian系でのaptロック待機時間(秒)
metricbeat_install_deb_lock_wait_seconds: 600
# 既存 Metricbeat パッケージ削除有無
metricbeat_remove_existing_package: true
# コンテナビルド用ランタイム
metricbeat_build_container_runtime: "docker"
# コンテナビルド用ネットワークモード
metricbeat_build_container_network_mode: "host"
# Metricbeat ビルド用コンテナイメージ
metricbeat_build_container_image_debian: "ubuntu:24.04"
metricbeat_build_container_image_rhel: "almalinux:9.6"
# Metricbeat ビルド時のworkdir
metricbeat_build_container_workdir: "/work"

#
# Metricbeat 配置先設定
#
# Metricbeat 設定ファイルを配置するディレクトリ
metricbeat_config_dir: "/etc/metricbeat"
# Metricbeat 設定ファイルのパス
metricbeat_config_file: "{{ metricbeat_config_dir }}/metricbeat.yml"
# Metricbeat データディレクトリ
metricbeat_data_dir: "/var/lib/metricbeat"
# Metricbeat ログディレクトリ
metricbeat_logs_dir: "/var/log/metricbeat"
# Metricbeat systemd unit ファイルのパス
metricbeat_systemd_unit_file: "/etc/systemd/system/metricbeat.service"

#
# Metricbeat 収集設定
#
# Metricbeat の HTTP 接続バインドアドレス
metricbeat_http_host: "0.0.0.0"
# Metricbeat の HTTP 接続ポート番号
metricbeat_http_port: 5067
# system メトリクス収集周期(単位: 秒)
metricbeat_system_period: 10s
# 送信先 Logstash のホスト名/IPアドレス
# IPアドレス又はFQDNを指定すること
# *.local などの multicast DNS 名は, 環境により名前解決が不安定になるため指定しないこと
# 解決処理の対応関係: 1) logging_backend_host が未定義又は空文字列でない場合はその値を採用,
# 2) logging_backend_host が未定義又は空文字列の場合は logging_backend グループ先頭ホスト名を取得,
# 3) 先頭ホストの ansible_host が定義されていれば優先し, 未定義の場合はホスト名を採用。
metricbeat_backend_host: >-
  {{
    (logging_backend_host | string | trim)
    if (logging_backend_host is defined and (logging_backend_host | string | trim | length) > 0)
    else (hostvars[groups['logging_backend'][0]].ansible_host | default(groups['logging_backend'][0]))
  }}
# 送信先 Logstash のポート番号
metricbeat_backend_port: 5044

#
# 起動検証設定
#
# Metricbeat コンテナの起動検証時の接続先ホスト名/IPアドレス
metricbeat_wait_host: "127.0.0.1"
# Metricbeat コンテナの起動検証時のタイムアウト値(単位: 秒)
metricbeat_wait_timeout: 120
# Metricbeat コンテナの起動検証時の待機開始遅延時間(単位: 秒)
metricbeat_wait_delay: 2
# Metricbeat コンテナの起動検証時のポーリング周期(単位: 秒)
metricbeat_wait_sleep: 2
# Metricbeat コンテナの起動検証時の接続元ホスト名/IPアドレス
metricbeat_wait_delegate_to: "{{ inventory_hostname }}"
# Metricbeat コンテナの起動検証時の再試行回数(単位: 回)
metricbeat_wait_retries: 5
