#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#  bash関連ファイル・ディレクトリ作成関連タスク

#
# bash用のプロキシ設定ファイルの生成
#
- name: Deploy a proxy setting file for Bash
  ansible.builtin.template:
    src: _bshrc.proxy.j2
    dest: /etc/skel/.bashrc.proxy
    owner: root
    group: root
    mode: '0644'
    backup: false

#
# bash用のLmod設定ファイルの生成
#
- name: Deploy a Lmod setting file for Bash
  ansible.builtin.template:
    src: _bshrc.lmod.j2
    dest: /etc/skel/.bashrc.lmod
    owner: root
    group: root
    mode: '0644'
    backup: false

#
# .bash_profile のスケルトンファイル生成
#
- name: Deploy a bash_profile skeleton
  ansible.builtin.template:
    src: _bash_profile.j2
    dest: /etc/skel/.bash_profile
    owner: root
    group: root
    mode: '0644'
    backup: false

#
# .bashrcのスケルトンに個人設定ファイル読込行を追加する
#
- name: Add sourcing personal setting line into /etc/skel/.bashrc
  ansible.builtin.lineinfile:
    path: /etc/skel/.bashrc
    regexp: '^\[ \-f ${HOME}/.bashrc.mine \] && source ${HOME}/.bashrc.mine'
    insertafter: EOF
    line: '[ -f ${HOME}/.bashrc.mine ] && source ${HOME}/.bashrc.mine'
    backup: false

#
# .bashrc.mine のスケルトンファイル
#
- name: Deploy a bashrc.mine skeleton
  ansible.builtin.template:
    src: _bashrc.mine.j2
    dest: /etc/skel/.bashrc.mine
    owner: root
    group: root
    mode: '0644'
    backup: false
