#!/bin/bash

templates_dir=../templates

rm -f emacs-settings-list.txt
rm -f emacs-setting.yml
touch emacs-setting.yml
touch emacs-settings-list.txt
ls ${HOME}/.emacs.d/user_settings/*.el|grep -v 'init.el'|grep -v 'install-pkg-cmdline.el'|while read line
do
    bname=`basename ${line}`
    #echo ${bname}
    echo "(load \"${bname}\") ;; ${bname}" >> emacs-settings-list.txt
    template=${templates_dir}/_emacs_d__${bname}.j2
    rm -f ${template}
    touch ${template}
    cat <<EOF > ${template}
;;  Ansible playbook
;;  Copyright 2020 Takeharu KATO All Rights Reserved.
;; This file is generated by ansible.
{# 日付の取得 #}
;; last update: {{ '%Y-%m-%d %H:%M:%S %Z' | strftime(ansible_date_time.epoch) }}
;;

EOF
    cat ${line} >> ${template}

    cat <<EOF >> emacs-setting.yml
# ${bname}の導入
- name: Deploy /etc/skel/.emacs.d/user_settings/${bname}
  template:
    src: _emacs_d__${bname}.j2
    dest: /etc/skel/.emacs.d/user_settings/${bname}
    owner: root
    group: root
    mode: 0644
    backup: no

EOF


done
