#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  パッケージ関連処理
#

# インストール対象となる開発パッケージのリストを作成
# - go_lang_versionが指定されている場合は,
#   go_remove_packagesに指定されたOS 標準のGo パッケージを除外する
- name: Build devel package list
  ansible.builtin.set_fact:
    devel_packages_effective: >-
      {{
        ((go_lang_version | default('') | length > 0)
          | ternary(
              devel_packages | difference(go_remove_packages | default([])),
              devel_packages
            ))
      }}

# 開発パッケージのインストール
- name: Install devel packages
  ansible.builtin.package:
    pkg:
      '{{ devel_packages_effective }}'
    state: present
  notify: disable_gui
