#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  前提パッケージ導入
#
---

#
# Kubernetes クライアント導入の前提となるパッケージを導入する
#

# Python クライアントの前提パッケージを導入する
- name: Install python prereq packages
  ansible.builtin.package:
    name: "{{ k8s_devel_python_prereq_packages_effective }}"
    state: present
  when:
    - k8s_devel_python_client_enabled | bool
    - k8s_devel_python_client_install_via_pip | default(false) | bool
