#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  ロール固有変数のデフォルト値
#  group_vars/all/all.yml やhost_varsで上書き可能とするため,
#  ロール名/defaults/main.yml に定義している
---

# Logstash ロールを有効化する。
logging_logstash_enabled: false

#
# Logstash コンテナの実行基盤設定
#
# docker compose ファイルを配置するディレクトリ
logstash_compose_dir: "/srv/logstash"
# Logstash コンテナの名前
logstash_container_name: "logstash"

#
# Logstash イメージと設定
#
# Logstash API の接続ポート番号 (単位: 番)
logstash_http_port: 9600
# Logstash のパイプラインID
logstash_pipeline_id: "main"
# Logstash 監視機能の有効化フラグ
logstash_monitoring_enabled: true

# Logstash API の接続先エンドポイント URL (明示指定用)
logstash_endpoint_url_explicit: ""
# Logstash endpoint 接続時の TLS 検証モード。
# 利用可能値: off, none, full
logstash_tls_mode: "{{ logging_backend_default_tls_mode | default('none') }}"

#
# 起動検証設定
#
# Logstash コンテナの起動検証時の接続先ホスト名/IPアドレス
logstash_wait_host: "127.0.0.1"
# Logstash コンテナの起動検証時のタイムアウト値 (単位: 秒)
logstash_wait_timeout: 120
# Logstash コンテナの起動検証時の待機開始遅延時間 (単位: 秒)
logstash_wait_delay: 2
# Logstash コンテナの起動検証時のポーリング周期 (単位: 秒)
logstash_wait_sleep: 2
# Logstash コンテナの起動検証時の接続元ホスト名/IPアドレス
logstash_wait_delegate_to: "{{ inventory_hostname }}"
# Logstash コンテナの起動検証時の再試行回数 (単位: 回)
logstash_wait_retries: 5
